Descartes development
tdescartes/software-product-sprint pull request #2
Opened 2021-06-09 16:12 UTC by tdescartes

Design first page and add some basic css codes.

2021-06-10 21:57 UTC, dgalbraith33 requested changes

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/pom.xml
> +    <googleCloudProjectId>dtuyishime-sps-summer21</googleCloudProjectId>
FYI: In the future, this sort of change could be it's own PR to keep things separate.

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +      <!-- Main Start-->
I like how you marked the start and end of the sections. It helps readability a lot!

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +              <div class="container">
FYI: the CSS class name container is usually used for the top-level container of the page (i.e. the class you have called "main").

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita
nit: Don't have lines with more than 80-100 characters if possible.

In HTML you can add a line break without it showing up on the page.

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +
nit: drop these two blank lines of spacing.

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +                          <h3> Skills</h3>
nit: drop leading space before Skills

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +          <section class="about-section sec-padding">
I would say avoid having CSS classes that aren't defined (here about-section and sec-padding).

If you want to add styles for these in a future PR it is easy enough to add them back. But for now it makes things slightly less clear.

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/index.html
> +                          <div class="skill">
nit: similar thing here with "skill" and "skill-item" classes.

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/style.css
> +    background-image:linear-gradient(to bottom right, var(--pink-light), var(--cyan-light));
nit: add a space after "background-image:" to be consistent with the rest of the file.

2021-06-10 21:57 UTC, dgalbraith33 commented on portfolio/src/main/webapp/style.css
> +    font-family: 'Source Code Pro', monospace;
FYI the way font-family works (apologies if you're already aware of this) is that it tries to use the fonts listed from left to right. So if the "Source Code Pro" font is unavailable for some reason (maybe it can't be loaded). This will switch to a generic monospace font.

Because of this you may want to pick a more specific monospace font for the browser to use in that case. (There is a list here: https://www.w3.org/Style/Examples/007/fonts.en.html). You can test what it will look like if loading the external font fails by simply getting rid of the 'Source Code Pro' temporarily and reloading.

TL;DR in the end you could have something like "font-family: 'Source Code Pro', Courier New, monospace"

2021-06-16 07:15 UTC, tdescartes commented on portfolio/src/main/webapp/index.html
> +      <!-- Main Start-->
Thank you.

2021-06-17 18:07 UTC, closed without merging